eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411