eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888
spring:
  application:
    name: service-config
  cloud:
    config:
      label: master
    server:
      git:
        uri: https://github.com/forezp/SpringcloudConfig.git
        searchPaths: respo
        username:
        password: